// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiGenteEnLinea.Infrastructure.Persistence.Contexts;

#nullable disable

namespace MiGenteEnLinea.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiGenteDbContext))]
    [Migration("20260207012638_RemoveSuscripcionesPlanFK")]
    partial class RemoveSuscripcionesPlanFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            
            // Model snapshot - sin cambios estructurales en el modelo
            // Esta migración solo elimina una FK constraint física en la base de datos
            // El modelo de EF Core ya no incluía esta FK (ver SuscripcionConfiguration.cs)
            
            #pragma warning restore 612, 618
        }
    }
}
